name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Lua Code
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
          
      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4
        
      - name: Install stylua
        run: |
          cargo install stylua
          
      - name: Check Lua formatting
        run: |
          stylua --check lua/
          
  test:
    runs-on: ubuntu-latest
    name: Test Plugin
    strategy:
      matrix:
        neovim_version: ['v0.8.0', 'v0.9.0', 'nightly']
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Neovim
        uses: rhymond/setup-neovim@v0.2.0
        with:
          neovim-version: ${{ matrix.neovim_version }}
          
      - name: Basic Plugin Load Test
        run: |
          nvim --headless -c "lua require('jira-nvim')" -c "qa"